name: AI PR Reviewer

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  issue_comment:

permissions:
  issues: write
  pull-requests: write
  contents: write

jobs:
  review:
    runs-on: ubuntu-latest
    if: ${{ github.event.sender.type != 'Bot' }} # prevent infinite bot loops
    steps:
      - name: PR Agent
        uses: the-pr-agent/pr-agent@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_KEY: ${{ secrets.MISTRAL_API_KEY }}
          OPENAI.API_BASE: "https://api.mistral.ai/v1"
          CONFIG.MODEL: "openai/mistral-large-latest" # "openai/" prefix required for custom endpoints
          CONFIG.MODEL_WEAK: "openai/mistral-small-latest"
          CONFIG.FALLBACK_MODELS: '["openai/mistral-large-latest"]'
          github_action_config.auto_review: "true"
          github_action_config.auto_describe: "true"
          github_action_config.auto_improve: "true"
